spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/cytry
    username: root
    password: Chenyang0
  # session 失效时间
  session:
    timeout:86400
server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 #表示已删除
      logic-not-delete-value: 0 # 表示未删除
